use schema practice.public;

CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL')
  EMPTY_FIELD_AS_NULL = TRUE
  DATE_FORMAT = 'AUTO'
  TIMESTAMP_FORMAT = 'AUTO'
  BINARY_FORMAT = 'HEX'
  ESCAPE = 'NONE'
  ESCAPE_UNENCLOSED_FIELD = NONE
  VALIDATE_UTF8 = TRUE
  SKIP_BLANK_LINES = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  SKIP_BYTE_ORDER_MARK = TRUE
  ENCODING = 'UTF8';

CREATE OR REPLACE TABLE RAW_TABLE(
IOS_App_Id STRING,
Title STRING,
Developer_Name STRING,
Developer_IOS_Id STRING,
IOS_Store_Url STRING,
Seller_Official_Website STRING,
Age_Rating STRING,
Total_Average_Rating DECIMAL,
Total_Number_Of_Ratings INTEGER,
Average_Rating_For_Version DECIMAL,
Number_Of_Ratings_For_Version INTEGER,
Original_Release_Date TIMESTAMP,
Current_Version_Release_Date TIMESTAMP,
Price_USD DECIMAL,
Primary_Genre STRING,
All_Genres STRING,
Languages STRING,
Description_part1 STRING,
Description_part2 STRING,
Description_part3 STRING);

CREATE OR REPLACE TABLE STAGE_TABLE LIKE RAW_TABLE;
CREATE OR REPLACE TABLE MASTER_TABLE LIKE RAW_TABLE;

CREATE OR REPLACE STREAM RAW_STREAM ON TABLE RAW_TABLE;
CREATE OR REPLACE STREAM STAGE_STREAM ON TABLE STAGE_TABLE;


SELECT * FROM MASTER_TABLE LIMIT 20;







